name: IliManagementTEST

on: 
  workflow_dispatch:

jobs:
  manage-Ili:
    runs-on: ubuntu-latest

    permissions: 
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 25
        uses: actions/setup-java@v3
        with:
          java-version: '25'
          distribution: 'adopt'
      - name: ilimanagerInstalation
        uses: ch-sz-geo/interlis-actions/setup-ilimanager@v0(DEV)
        with:
          path: ../ilimanager
      - name: ili2cInstalation
        uses: ch-sz-geo/interlis-actions/setup-iliCompiler@v0(DEV)
        with:
          path: ../ili2c
      - name: verify java Version
        run: java --version
      - name: find ilimanager
        run: |
          ls
          echo "parent: "
          ls ..
          echo "Ilimanager:"
          ls ../ilimanager
